# Generated by Django 5.2.14 on 2026-06-01 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Restaurant', max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('pan_vat_no', models.CharField(blank=True, max_length=40, verbose_name='PAN/VAT number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('currency_code', models.CharField(default='NPR', max_length=8)),
                ('currency_symbol', models.CharField(default='Rs', max_length=8)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant settings',
                'verbose_name_plural': 'Restaurant settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx')],
            },
        ),
    ]
