# Generated by Django 5.2.14 on 2026-06-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='void_requested_qty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
