# Generated by Django 5.2.14 on 2026-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_void_reason_orderitem_void_requested_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_disposition',
            field=models.CharField(blank=True, choices=[('', '—'), ('VOIDED', 'Voided before cooking'), ('STASHED', 'Stashed to reheat'), ('WASTED', 'Wasted / discarded')], default='', max_length=10),
        ),
    ]
