# Generated by Django 5.2.14 on 2026-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('BANK', 'Bank / QR'), ('STAFF', 'Staff (salary deduction)'), ('OTHER', 'Other')], max_length=8),
        ),
    ]
