# Generated by Django 5.2.14 on 2026-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_packable',
            field=models.BooleanField(default=True),
        ),
    ]
