# Generated by Django 5.2.14 on 2026-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Reception'), ('WAITER', 'Waiter'), ('CHEF', 'Chef / Kitchen'), ('ACCOUNTANT', 'Accountant')], default='WAITER', max_length=10),
        ),
    ]
