# Generated by Django 5.2.14 on 2026-06-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('table_type', models.CharField(choices=[('NORMAL', 'Normal'), ('CABIN', 'Cabin')], default='NORMAL', max_length=10)),
                ('section', models.CharField(blank=True, help_text='Floor or area', max_length=40)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied'), ('BILLING', 'Billing')], default='FREE', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
